#!/usr/bin/env bash
#s script displays list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# to Display a user-oriented format
# to Show process hierarchy

ps -a -x -u -f
