#!/usr/bin/env bash
# This is the script displays
# to infinity and beyond indefinitely
# thisis With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
