#!/usr/bin/env bash
# This is  script creates the file /var/run/holbertonscript.pid containing its PID
# this is Displays To infinity and beyond indefinitely
# this is to Display I hate the kill command when receiving a SIGTERM signal
# this is to Display Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

function love() {
    rm /var/run/holbertonscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while [ true ]; do
    echo To infinity and beyond;
done
